fn

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -1,66 +1,15 @@
-name: CI
-
-on: [push, pull_request]
-
+name: 'CI'
+on:
+  pull_request:
 jobs:
-  build:
+  build-test:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.8'
-
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r Requirements/Requirements.txt
-        sudo apt-get update
-        sudo apt-get install -y libnss3 lsof
-
-    - name: Install Allure CLI
-      run: |
-        npm install -g allure-commandline --save-dev
-
-    - name: Run tests
-      run: |
-        pytest --alluredir=allure-results --junitxml=pytest-results.xml
-
-    - name: Get Allure history
-      uses: actions/checkout@v2
-      if: always()
-      continue-on-error: true
-      with:
-        ref: gh-pages
-        path: gh-pages
-
-    - name: Allure Report action from marketplace
-      uses: simple-elf/allure-report-action@master
-      if: always()
-      id: allure-report
-      with:
-        allure_results: allure-results
-        gh_pages: gh-pages
-        allure_report: allure-report
-        allure_history: allure-history
-
-    - name: Deploy report to Github Pages
-      if: always()
-      uses: peaceiris/actions-gh-pages@v2
-      env:
-        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        PUBLISH_BRANCH: gh-pages
-        PUBLISH_DIR: allure-history
-
-    - name: Create test-results
-      uses: actions/upload-artifact@v4  
-      if: success() || failure()        
-      with:
+      - uses: actions/checkout@v4         # checkout the repo
+      - run: npm ci                       # install packages
+      - run: npm test                     # run tests (configured to use jest-junit reporter)
+      - uses: actions/upload-artifact@v4  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
           name: test-results
-          path: pytest-results.xml
-
-    
+          path: jest-junit.xml
